FROM python:3.4-alpine

ENV PYTHONUNBUFFERED 1

RUN apk update \
  && apk add --virtual build-deps gcc python3-dev musl-dev libffi-dev

RUN addgroup -S -g 1002 django \
    && adduser -S -G django -u 1002 django

COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt \
    && rm /requirements.txt

COPY ./reset_db.sh /reset_db.sh
RUN sed -i 's/\r$//g' /reset_db.sh
RUN chmod +x /reset_db.sh
RUN chown django /reset_db.sh

COPY ./runpublic.sh /runpublic.sh
RUN sed -i 's/\r$//g' /runpublic.sh
RUN chmod +x /runpublic.sh
RUN chown django /runpublic.sh

RUN mkdir /app && \
    chown -R django /app

USER django

VOLUME ["/app"]

WORKDIR /app
