# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0038_auto_20150921_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 18, 50, 19, 147379, tzinfo=utc), verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 18, 50, 19, 150766, tzinfo=utc), verbose_name='date due'),
        ),
    ]
