# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 23:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0038_auto_20150921_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 23, 13, 0, 746283, tzinfo=utc), verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 23, 13, 0, 748898, tzinfo=utc), verbose_name='date due'),
        ),
    ]
