# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0039_auto_20160509_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 19, 29, 50, 523171, tzinfo=utc), verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 19, 29, 50, 526832, tzinfo=utc), verbose_name='date due'),
        ),
    ]
