from django.conf.urls import patterns, url

from taskManager import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^logout/$', views.logout_view, name = 'logout_user'),
	url(r'^download/(?P<file_id>\d+)/$', views.download_file, name = 'download_file'),
	url(r'^downloadprofilepic/(?P<user_id>\d+)/$', views.download_profile_pic, name = 'download_profile_pic'),
	url(r'^(?P<project_id>\d+)/$', views.proj_details, name = 'proj_details'),
	url(r'^(?P<project_id>\d+)/newtask/$', views.new_task, name = 'new_task'),
	url(r'^(?P<project_id>\d+)/newfile/$', views.new_file, name = 'new_file'),
	url(r'^(?P<project_id>\d+)/(?P<task_id>\d+)/$', views.task_details, name = 'task_details'),
	url(r'^(?P<project_id>\d+)/(?P<task_id>\d+)/newnote/$', views.new_note, name = 'new_note'),
	url(r'^(?P<project_id>\d+)/(?P<task_id>\d+)/editnote/(?P<note_id>\d+)$', views.edit_note, name = 'edit_note'),
	url(r'^(?P<project_id>\d+)/(?P<task_id>\d+)/deletenote/(?P<note_id>\d+)$', views.delete_note, name = 'delete_note'),
	url(r'^register/$', views.register, name = 'register'),
	url(r'^login/$', views.login_view, name = 'login'),
	url(r'^newproject/$', views.new_project, name= 'new_project'),
	url(r'^(?P<project_id>\d+)/edit_project/$', views.edit_project, name = 'edit_project'),
	url(r'^manage_groups/$', views.manage_groups, name = 'manage_groups'),
	url(r'^manage_projects/$', views.manage_projects, name = 'manage_projects'),
	url(r'^(?P<project_id>\d+)/edit_task/(?P<task_id>\d+)$', views.edit_task, name = 'edit_task'),
	url(r'^(?P<project_id>\d+)/delete_task/(?P<task_id>\d+)$', views.delete_task, name = 'delete_task'),
	url(r'^(?P<project_id>\d+)/complete_task/(?P<task_id>\d+)$', views.complete_task, name = 'complete_task'),
	url(r'^(?P<project_id>\d+)/manage_tasks/$', views.manage_tasks, name = 'manage_tasks'),
	url(r'^(?P<project_id>\d+)/delete_project/$', views.delete_project, name = 'delete_project'),
	url(r'^dashboard/$', views.dashboard, name = 'dashboard'),
	url(r'^profile/$', views.profile, name = 'profile'),
	url(r'^change_password/$', views.change_password, name = 'change_password'),
	url(r'^my_projects/$', views.my_projects, name = 'my_projects'),
	url(r'^my_tasks/$', views.my_tasks, name = 'my_tasks'),
        url(r'^search/$', views.search, name = 'search'),
	url(r'^profile/(?P<user_id>\d+)$', views.profile_by_id, name = 'profile_by_id'),
	url(r'^tutorials/$', views.tutorials, name = 'tutorials'),
	url(r'^tutorials/(?P<vuln_id>[a-z\-]+)/$', views.show_tutorial, name = 'show_tutorial'),
)